### ISSUE TITLE
gdt32.s structure query

### ISSUE THREAD

**Issue by aunxx** [thass0/blog-code#2]
Fantastic article and description, but I've a question around the gdt32.s file that I cannot find an answer to.

The gdt32_data_segment:  element seems to be 72 bits long rather than the expected 64 bit stated value. 
(dw + dw + db + db + db + dw)  -- (72 bits)

which doesn't match gdt32_code_segment: 
(dw + dw + db + db + db + db)  -- (64 bits)

I do not believe it makes any real difference to the final code other than boundaries, I was just curious to see if I was missing something.

**Comment by thass0** [comment]
Yes, you are correct, that's wrong. Thank you for pointing out my mistake. I'll update this post and code.
